using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._CE.LockKey.LockPickingMinigame.UI;

[GenerateTypedNameReferences]
public sealed partial class CELockPickingMinigameWindow : BaseWindow
{
    public CELockPickingMinigameWindow()
    {
        RobustXamlLoader.Load(this);
    }
}

