using Content.Client.Resources;
using Content.Shared._CE.LockKey.LockPickingMinigame;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.ResourceManagement;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Utility;

namespace Content.Client._CE.LockKey.LockPickingMinigame.UI;

[GenerateTypedNameReferences]
public sealed partial class CELockPickingMinigameWindow : BaseWindow
{
    [Dependency] private readonly IResourceCache _resourceCache = default!;

    private const int ElementWidth = 32;
    private const int ElementHeight = 64;

    private CELockPickingMinigamePrototype? _lockPickingStyle;
    private Texture? _lockpickTexture;
    public CELockPickingMinigameWindow()
    {
        RobustXamlLoader.Load(this);
    }

    /// <summary>
    /// Initialize new minigame window
    /// </summary>
    /// <param name="lockPickingStyle">Style of lockpicking minigame</param>
    /// <param name="lockpick">Lockpick texture path</param>
    /// <param name="lockLength">Lock length</param>
    public void InitVisuals(CELockPickingMinigamePrototype lockPickingStyle, ResPath lockpick, int lockLength)
    {
        LockPickingWindow.Visible = false;

        _lockPickingStyle = lockPickingStyle;

        var genericPanel = new PanelContainer
        {
            SetWidth = (lockLength + 1) * ElementWidth,
            SetHeight = ElementHeight,
        };

        switch (lockLength)
        {
            case 0:
                return;

            case 1:
                var pinPathTexture = _resourceCache.GetTexture(_lockPickingStyle.PinPath.SinglePinPath);
                var pinPath = new PanelContainer
                {
                    PanelOverride = new StyleBoxTexture
                    {
                        Texture = pinPathTexture,
                    },
                    SetWidth = ElementWidth,
                    SetHeight = ElementHeight,
                };
                genericPanel.AddChild(pinPath);
                break;
        }

        LockPickingWindow.AddChild(genericPanel);
    }
}

